export const DEMO_HEADLINES_POLL_MS = 60_000;
export const DEMO_HEADLINES_SUPPORTED_PERSISTENT_TABS = 3;
export const DEMO_HEADLINES_BURST_PER_MINUTE = 5;
export const DEMO_HEADLINES_DAILY_LIMIT = 5_000;
