/**
 * Static Next route loaders for call_api. Specifiers must be literal so
 * the bundler can trace them. Keys are app/api route ids. The freshness
 * test fails if this map drifts from advertised Next-only pins.
 */

export type NextRouteModule = Record<string, unknown>;

export const NEXT_MODULES: Record<string, () => Promise<NextRouteModule>> = {
  "alerts": () => import("@/app/api/alerts/route") as Promise<NextRouteModule>,
  "alerts/[id]": () => import("@/app/api/alerts/[id]/route") as Promise<NextRouteModule>,
  "blotter": () => import("@/app/api/blotter/route") as Promise<NextRouteModule>,
  "bookmarks": () => import("@/app/api/bookmarks/route") as Promise<NextRouteModule>,
  "bookmarks/[post_id]": () => import("@/app/api/bookmarks/[post_id]/route") as Promise<NextRouteModule>,
  "bpi": () => import("@/app/api/bpi/route") as Promise<NextRouteModule>,
  "breadth": () => import("@/app/api/breadth/route") as Promise<NextRouteModule>,
  "cor": () => import("@/app/api/cor/route") as Promise<NextRouteModule>,
  "credit-spread": () => import("@/app/api/credit-spread/route") as Promise<NextRouteModule>,
  "discover": () => import("@/app/api/discover/route") as Promise<NextRouteModule>,
  "dispersion": () => import("@/app/api/dispersion/route") as Promise<NextRouteModule>,
  "divyield": () => import("@/app/api/divyield/route") as Promise<NextRouteModule>,
  "equibles-ats-venue-share": () => import("@/app/api/equibles-ats-venue-share/route") as Promise<NextRouteModule>,
  "equibles-cot-positioning": () => import("@/app/api/equibles-cot-positioning/route") as Promise<NextRouteModule>,
  "equibles-filing-forensics": () => import("@/app/api/equibles-filing-forensics/route") as Promise<NextRouteModule>,
  "equibles-short-crowding": () => import("@/app/api/equibles-short-crowding/route") as Promise<NextRouteModule>,
  "equibles-smart-money-13f": () => import("@/app/api/equibles-smart-money-13f/route") as Promise<NextRouteModule>,
  "flex-token": () => import("@/app/api/flex-token/route") as Promise<NextRouteModule>,
  "flow-surprise": () => import("@/app/api/flow-surprise/route") as Promise<NextRouteModule>,
  "futures-quote": () => import("@/app/api/futures-quote/route") as Promise<NextRouteModule>,
  "gamma-rotation": () => import("@/app/api/gamma-rotation/route") as Promise<NextRouteModule>,
  "garch-convergence": () => import("@/app/api/garch-convergence/route") as Promise<NextRouteModule>,
  "gex": () => import("@/app/api/gex/route") as Promise<NextRouteModule>,
  "hhlev": () => import("@/app/api/hhlev/route") as Promise<NextRouteModule>,
  "hyad": () => import("@/app/api/hyad/route") as Promise<NextRouteModule>,
  "iei-hyg": () => import("@/app/api/iei-hyg/route") as Promise<NextRouteModule>,
  "index-quote": () => import("@/app/api/index-quote/route") as Promise<NextRouteModule>,
  "internals": () => import("@/app/api/internals/route") as Promise<NextRouteModule>,
  "ivrank": () => import("@/app/api/ivrank/route") as Promise<NextRouteModule>,
  "journal": () => import("@/app/api/journal/route") as Promise<NextRouteModule>,
  "journal/sync": () => import("@/app/api/journal/sync/route") as Promise<NextRouteModule>,
  "leap": () => import("@/app/api/leap/route") as Promise<NextRouteModule>,
  "ma-ratio": () => import("@/app/api/ma-ratio/route") as Promise<NextRouteModule>,
  "margin-debt": () => import("@/app/api/margin-debt/route") as Promise<NextRouteModule>,
  "menthorq/[command]/image": () => import("@/app/api/menthorq/[command]/image/route") as Promise<NextRouteModule>,
  "menthorq/cta": () => import("@/app/api/menthorq/cta/route") as Promise<NextRouteModule>,
  "menthorq/cta/image": () => import("@/app/api/menthorq/cta/image/route") as Promise<NextRouteModule>,
  "models": () => import("@/app/api/models/route") as Promise<NextRouteModule>,
  "newsfeed/posts": () => import("@/app/api/newsfeed/posts/route") as Promise<NextRouteModule>,
  "options/rv-ratio": () => import("@/app/api/options/rv-ratio/route") as Promise<NextRouteModule>,
  "orders": () => import("@/app/api/orders/route") as Promise<NextRouteModule>,
  "performance": () => import("@/app/api/performance/route") as Promise<NextRouteModule>,
  "portfolio": () => import("@/app/api/portfolio/route") as Promise<NextRouteModule>,
  "previous-close": () => import("@/app/api/previous-close/route") as Promise<NextRouteModule>,
  "prices": () => import("@/app/api/prices/route") as Promise<NextRouteModule>,
  "profile": () => import("@/app/api/profile/route") as Promise<NextRouteModule>,
  "regime": () => import("@/app/api/regime/route") as Promise<NextRouteModule>,
  "risk-free-rate": () => import("@/app/api/risk-free-rate/route") as Promise<NextRouteModule>,
  "scanner": () => import("@/app/api/scanner/route") as Promise<NextRouteModule>,
  "scanner/strength": () => import("@/app/api/scanner/strength/route") as Promise<NextRouteModule>,
  "scanner/strength/scan": () => import("@/app/api/scanner/strength/scan/route") as Promise<NextRouteModule>,
  "scanner/theta": () => import("@/app/api/scanner/theta/route") as Promise<NextRouteModule>,
  "scanner/theta/scan": () => import("@/app/api/scanner/theta/scan/route") as Promise<NextRouteModule>,
  "service-health": () => import("@/app/api/service-health/route") as Promise<NextRouteModule>,
  "skew": () => import("@/app/api/skew/route") as Promise<NextRouteModule>,
  "skew2d": () => import("@/app/api/skew2d/route") as Promise<NextRouteModule>,
  "straddle": () => import("@/app/api/straddle/route") as Promise<NextRouteModule>,
  "ticker/info": () => import("@/app/api/ticker/info/route") as Promise<NextRouteModule>,
  "ticker/news": () => import("@/app/api/ticker/news/route") as Promise<NextRouteModule>,
  "ticker/seasonality": () => import("@/app/api/ticker/seasonality/route") as Promise<NextRouteModule>,
  "trin": () => import("@/app/api/trin/route") as Promise<NextRouteModule>,
  "vcg": () => import("@/app/api/vcg/route") as Promise<NextRouteModule>,
  "vixcor": () => import("@/app/api/vixcor/route") as Promise<NextRouteModule>,
  "vixts": () => import("@/app/api/vixts/route") as Promise<NextRouteModule>,
  "vol-cone": () => import("@/app/api/vol-cone/route") as Promise<NextRouteModule>,
  "watchlist": () => import("@/app/api/watchlist/route") as Promise<NextRouteModule>,
  "watchlist/[symbol]": () => import("@/app/api/watchlist/[symbol]/route") as Promise<NextRouteModule>,
  "workflow": () => import("@/app/api/workflow/route") as Promise<NextRouteModule>,
  "yield-curve": () => import("@/app/api/yield-curve/route") as Promise<NextRouteModule>,
  "yield-curve/live": () => import("@/app/api/yield-curve/live/route") as Promise<NextRouteModule>,
};
