"""Versioned measurement registry; availability is established by collection, not registration."""

_SOURCE_ROWS = [
    (
        "openrouter",
        "OpenRouter",
        "https://openrouter.ai/docs/cookbook/administration/data-api",
        "daily",
        "Authenticated data API; public rankings data is CC BY 4.0 with attribution",
    ),
    (
        "vercel",
        "Vercel AI Gateway",
        "https://vercel.com/docs/ai-gateway/leaderboards",
        "daily",
        "Public publisher export under CC BY 4.0; attribution required",
    ),
    (
        "gpu-rental",
        "GPU Rental Prices",
        "https://github.com/adriannutiu/gpu-rental-prices/tree/main/data/snapshots",
        "daily",
        "Public historical snapshots under CC BY 4.0; upstream asking-price provenance retained",
    ),
    ("lambda", "Lambda", "https://lambda.ai/pricing", "daily", "Public asking prices; bundle terms retained"),
    (
        "artificial-analysis",
        "Artificial Analysis",
        "https://artificialanalysis.ai/data-api",
        "daily",
        "Entitlement-dependent; internal-only until redistribution rights verified",
    ),
    (
        "sec",
        "SEC EDGAR",
        "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
        "filing",
        "Public filings; fair-access user agent and rate limits apply",
    ),
    (
        "issuer-disclosures",
        "Issuer disclosures",
        "https://www.sec.gov/edgar/search/",
        "filing",
        "Primary issuer documents; retain exact definition and filing provenance",
    ),
    (
        "vast",
        "Vast.ai",
        "https://docs.vast.ai/api-reference/search/search-offers",
        "daily",
        "Authenticated read-only offers; account entitlement required",
    ),
    (
        "eia",
        "EIA",
        "https://www.eia.gov/electricity/gridmonitor/",
        "hourly",
        "Public official measurements; API key required",
    ),
    (
        "noaa",
        "NOAA",
        "https://www.ncei.noaa.gov/access/services/data/v1",
        "daily",
        "Public U.S. government daily summaries; fixed-station coverage is reported",
    ),
    (
        "portkey",
        "Portkey",
        "https://portkey.ai/rankings/daily",
        "daily",
        "Experimental; automation and estimation methodology unverified",
    ),
    (
        "ramp",
        "Ramp AI Index",
        "https://ramp.com/data/ai-index",
        "monthly",
        "Public published research curated from credential-free HTML; Ramp Data API out of scope for v1",
    ),
    (
        "open-design-arena",
        "OpenDesign Arena",
        "https://open-design.ai/llm-arena-for-design/",
        "snapshot",
        "Public design-task leaderboard HTML; LLM/model-quality only, never GPU scarcity",
    ),
    (
        "ib",
        "Interactive Brokers",
        "https://www.interactivebrokers.com/",
        "live",
        "Account market-data entitlement; existing internal feed only",
    ),
    (
        "uw",
        "Unusual Whales",
        "https://api.unusualwhales.com/docs",
        "daily",
        "Account API entitlement; existing internal feed only",
    ),
]
SOURCES = {
    id: dict(
        id=id,
        name=name,
        url=url,
        cadence=cadence,
        license=license,
        lineage_group="gpu-aggregator" if id == "gpu-rental" else id,
    )
    for id, name, url, cadence, license in _SOURCE_ROWS
}

_ROWS = [
    (
        "D1",
        "Public routed token activity",
        "demand",
        "P0",
        ["openrouter"],
        [],
        "Complete UTC days; total includes other. Visible non-free tokens are not billed tokens. 7-day mean and matched 28-day growth.",
    ),
    (
        "D2",
        "Application activity",
        "demand",
        "P1",
        ["openrouter"],
        [],
        "Requests, tokens per request and concentration within the returned cohort; shared OpenRouter lineage.",
    ),
    (
        "D3",
        "Gateway mix",
        "demand",
        "P0",
        ["vercel"],
        [],
        "Token, request and spend shares kept separate. Spend share / token share is relative monetization, not dollar ASP.",
    ),
    (
        "D4",
        "Independent host observations",
        "demand",
        "P2",
        ["portkey"],
        [],
        "Experimental publisher activity; estimated spend excluded from confirmation.",
    ),
    (
        "D5",
        "Ramp business AI spend",
        "demand",
        "P0",
        ["ramp"],
        ["MSFT", "AMZN", "GOOGL", "META", "ORCL"],
        "Monthly median, top-10% and top-1% AI spend per employee from Ramp card and bill-pay transactions. Paid usage only; free tools excluded. Top-1% cohort is volatile.",
    ),
    (
        "D6",
        "OpenDesign Arena model quality",
        "demand",
        "P2",
        ["open-design-arena"],
        [],
        "Published design-task average score, cost per artifact and completion time by model and task family (overall, web, mobile, desktop, dashboard, landing). LLM/model-quality only; never GPU scarcity or Silicon Data.",
    ),
    (
        "C1",
        "Matched GPU asking prices",
        "compute",
        "P0",
        ["lambda", "gpu-rental"],
        ["NVDA", "AMD"],
        "Fixed provider, region, GPU, VRAM, count, interconnect, tenancy and term. Provider-balanced geometric price relatives; spot separate.",
    ),
    (
        "C2",
        "Rentable GPU availability",
        "compute",
        "P1",
        ["vast"],
        ["NVDA", "AMD"],
        "Verified rentable offers, machines and GPU counts in fixed filters. Disappearance does not imply rental or fleet utilization.",
    ),
    (
        "C3",
        "Inference price basket",
        "compute",
        "P0",
        ["artificial-analysis"],
        [],
        "Versioned fixed models and token bundle. Missing members suppress the basket; legacy v1 remains separate.",
    ),
    (
        "C4",
        "Fixed-task economics",
        "compute",
        "P1",
        ["artificial-analysis"],
        [],
        "Cost per successful task requires licensed benchmark, accuracy, latency and context constraints; arbitrary benchmark division prohibited.",
    ),
    (
        "H1",
        "Hardware delivery and guidance",
        "delivery",
        "P0",
        ["sec", "issuer-disclosures"],
        ["NVDA", "DELL"],
        "NVIDIA data-center revenue is separate from total-company guidance. Orders, revenue and backlog retain issuer definitions.",
    ),
    (
        "H2",
        "Channel working capital",
        "delivery",
        "P1",
        ["sec", "issuer-disclosures"],
        ["NVDA", "DELL", "SMCI", "MU", "TSM"],
        "DIO/DSO use average beginning and ending balances, quarterly flow and actual fiscal days.",
    ),
    (
        "F1",
        "Cash investment coverage",
        "finance",
        "P0",
        ["sec", "issuer-disclosures"],
        ["MSFT", "AMZN", "GOOGL", "META", "ORCL"],
        "Fiscal YTD differences produce quarters, then TTM OCF / cash PP&E. Aggregate ratios require synchronized periods and reconciled definitions; capex is not AI-only.",
    ),
    (
        "F2",
        "Conversion and funding quality",
        "finance",
        "P1",
        ["sec", "issuer-disclosures"],
        ["MSFT", "AMZN", "GOOGL", "META", "ORCL"],
        "RPO conversion, leases and obligations keep issuer period and counterparty definitions; cloud revenue is not AI revenue.",
    ),
    (
        "P1",
        "Physical grid activity",
        "delivery",
        "P1",
        ["eia", "noaa"],
        ["VRT", "ETN"],
        "Observed DOM sub-BA load is not PJM aggregate or AI MW. Weather/calendar residual requires sufficient aligned history and control-region validation.",
    ),
    (
        "P2",
        "Power delivery milestones",
        "delivery",
        "P1",
        ["issuer-disclosures"],
        ["VRT", "ETN"],
        "Requested, contracted, construction and energized MW remain distinct; deduplicate project phases. Retain issuer order horizons.",
    ),
    (
        "M1",
        "Market pricing context",
        "finance",
        "P0",
        ["ib", "uw"],
        ["NVDA", "AMD", "MSFT", "AMZN", "GOOGL", "ORCL", "DELL", "SMCI", "VRT", "ETN"],
        "Existing ticker feeds own prices, IV, institutional flow and next-day OI. Context cannot establish edge or a Kelly probability.",
    ),
]
INDICATORS = {
    id: dict(
        id=id, title=title, pane=pane, priority=priority, source_ids=sources, tickers=tickers, methodology=methodology
    )
    for id, title, pane, priority, sources, tickers, methodology in _ROWS
}
