"""CIP-014 loadfile slice: reaping, git locks, and the launchd pre-lock program."""

from scripts.tests.loop_lifecycle_adversarial_lib import (
    test_reclaim_reaps_the_dead_owners_recorded_agents_and_nothing_else,
    test_an_untracked_orphan_in_the_clone_is_never_reaped,
    test_a_declared_pid_is_reaped_only_when_it_is_really_the_rounds,
    test_a_prompt_declaration_is_reaped_with_its_children,
    test_a_late_or_sloppy_declaration_is_ignored,
    test_a_pidfile_line_never_joins_two_numbers,
    test_descendant_expansion_never_crosses_into_a_remote_control_process,
    test_the_recorded_set_stays_bounded_by_what_is_alive,
    test_a_reaped_processs_children_go_with_it,
    test_a_recycled_pid_in_the_sampled_set_is_not_reaped,
    test_reclaim_kills_the_recorded_round_group_even_outside_the_clone_tree,
    test_a_round_record_naming_a_process_outside_the_clone_is_ignored,
    test_a_record_planted_inside_the_clone_is_ignored,
    test_the_next_run_after_a_sigkilled_wrapper_stops_the_orphaned_agent,
    test_abandoned_git_locks_are_cleared_and_live_shared_ones_kept,
    test_launchd_gives_the_wrapper_time_to_reap_and_page,
    test_launchd_does_not_skip_the_night_for_a_reused_pid,
    test_launchd_stands_down_loudly_for_a_live_owner,
    test_launchd_does_not_stand_down_for_a_garbage_pid,
    test_launchd_retries_the_fetch_then_fails_loudly_without_running_the_clone,
    test_launchd_recovers_from_a_transient_fetch_failure,
    test_launchd_clears_abandoned_git_locks_before_the_checkout,
    test_launchd_names_a_missing_timeout_binary,
    test_no_loop_skill_tells_the_agent_to_verify_the_runner_lock,
)

__all__ = [
    test_reclaim_reaps_the_dead_owners_recorded_agents_and_nothing_else,
    test_an_untracked_orphan_in_the_clone_is_never_reaped,
    test_a_declared_pid_is_reaped_only_when_it_is_really_the_rounds,
    test_a_prompt_declaration_is_reaped_with_its_children,
    test_a_late_or_sloppy_declaration_is_ignored,
    test_a_pidfile_line_never_joins_two_numbers,
    test_descendant_expansion_never_crosses_into_a_remote_control_process,
    test_the_recorded_set_stays_bounded_by_what_is_alive,
    test_a_reaped_processs_children_go_with_it,
    test_a_recycled_pid_in_the_sampled_set_is_not_reaped,
    test_reclaim_kills_the_recorded_round_group_even_outside_the_clone_tree,
    test_a_round_record_naming_a_process_outside_the_clone_is_ignored,
    test_a_record_planted_inside_the_clone_is_ignored,
    test_the_next_run_after_a_sigkilled_wrapper_stops_the_orphaned_agent,
    test_abandoned_git_locks_are_cleared_and_live_shared_ones_kept,
    test_launchd_gives_the_wrapper_time_to_reap_and_page,
    test_launchd_does_not_skip_the_night_for_a_reused_pid,
    test_launchd_stands_down_loudly_for_a_live_owner,
    test_launchd_does_not_stand_down_for_a_garbage_pid,
    test_launchd_retries_the_fetch_then_fails_loudly_without_running_the_clone,
    test_launchd_recovers_from_a_transient_fetch_failure,
    test_launchd_clears_abandoned_git_locks_before_the_checkout,
    test_launchd_names_a_missing_timeout_binary,
    test_no_loop_skill_tells_the_agent_to_verify_the_runner_lock,
]
