#!/usr/bin/env bash
# Provision the non-Claude agent-CLI providers the nightly loops fall back to.
#
# Everything this writes lives OUTSIDE any Radon clone, under
# ~/.radon/agent-cli. That is deliberate: the loops' credential rails refuse a
# key file inside the clone, and a `git clean` between phases would delete one
# anyway. Nothing here is secret-generating — it only records where a key
# already on this host can be read from, and how to reach each provider.
#
# Idempotent. Safe to re-run. Never invoked from inside a nightly wrapper.
#
#   scripts/agent_cli_bootstrap.sh          # provision, then report
#   scripts/agent_cli_bootstrap.sh --check  # report only, exit 1 if incomplete
set -Eeuo pipefail

ROOT="${RADON_AGENT_CLI_ROOT:-$HOME/.radon/agent-cli}"
CHECK_ONLY=0
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=1

# grok's CLI is the host for every OpenAI-compatible provider, because it is
# the only agent CLI here that speaks /chat/completions. codex speaks only
# /responses, which NVIDIA NIM and Cerebras do not serve (verified 2026-09-06:
# both 404). A rung's `--model` names the `[model."<id>"]` key below.
#
# NVIDIA's own nvidia/* models are the only NIM models usable through grok:
# third-party ones (kimi-k3, deepseek-v4-pro, minimax-m3) answer correctly and
# then exit 1 on `serialization error: invalid type: null, expected u32`,
# because NIM returns `usage.prompt_tokens_details.audio_tokens: null` for
# them and grok's client wants a u32. An exit code is what the wrapper reads,
# so a model that cannot produce a clean one is not a rung.
NVIDIA_MODEL="${RADON_NVIDIA_MODEL:-nvidia/nemotron-3-ultra-550b-a55b}"
CEREBRAS_MODEL="${RADON_CEREBRAS_MODEL:-qwen-3.8-27b}"

log() { printf '[agent-cli] %s\n' "$*"; }

write_grok_home() {
  local tag="$1" base_url="$2" env_key="$3" model="$4"
  local home="$ROOT/grok-home-$tag"
  mkdir -p "$home"
  cat > "$home/config.toml.new" <<EOF
# Generated by scripts/agent_cli_bootstrap.sh. Do not hand-edit.
# The grok CLI hosts this provider; the model key is what a ladder rung's
# --model names, so it must stay byte-identical to the rung's model id.
[model."$model"]
base_url = "$base_url"
env_key = "$env_key"
model = "$model"
EOF
  mv -f "$home/config.toml.new" "$home/config.toml"
  chmod 0700 "$home"
  log "wrote $home/config.toml ($model)"
}

# One env file, mode 0600, read by the wrappers before they launch a rung.
# Values are sourced from the environment if present, else carried forward
# from the existing file, so re-running never blanks a key.
carry() {
  local key="$1" cur="${2:-}" val="${!key:-}"
  [[ -n "$val" ]] && { printf '%s' "$val"; return 0; }
  printf '%s' "$cur"
}

provision() {
  mkdir -p "$ROOT"
  chmod 0700 "$ROOT"
  local envf="$ROOT/env" old_nv="" old_cb="" old_xai=""
  if [[ -r "$envf" ]]; then
    old_nv="$(sed -n 's/^NVIDIA_API_KEY=//p' "$envf" | head -1)"
    old_cb="$(sed -n 's/^CEREBRAS_API_KEY=//p' "$envf" | head -1)"
    old_xai="$(sed -n 's/^XAI_API_KEY=//p' "$envf" | head -1)"
  fi
  umask 077
  {
    echo "# Generated by scripts/agent_cli_bootstrap.sh. Mode 0600."
    echo "# Provider keys for the nightly fallback ladder. NOT a Radon .env:"
    echo "# it holds no broker, Turso or Anthropic credential, and lives"
    echo "# outside every clone so the loops' rails never have to trust it."
    echo "NVIDIA_API_KEY=$(carry NVIDIA_API_KEY "$old_nv")"
    echo "CEREBRAS_API_KEY=$(carry CEREBRAS_API_KEY "$old_cb")"
    echo "XAI_API_KEY=$(carry XAI_API_KEY "$old_xai")"
  } > "$envf.new"
  mv -f "$envf.new" "$envf"
  chmod 0600 "$envf"
  log "wrote $envf"

  write_grok_home nvidia   "https://integrate.api.nvidia.com/v1" NVIDIA_API_KEY   "$NVIDIA_MODEL"
  write_grok_home cerebras "https://api.cerebras.ai/v1"          CEREBRAS_API_KEY "$CEREBRAS_MODEL"
}

report() {
  local missing=0 v
  # codex: ChatGPT subscription, refreshed by the CLI itself.
  if [[ -r "${CODEX_HOME:-$HOME/.codex}/auth.json" ]]; then
    log "codex     OK   ${CODEX_HOME:-$HOME/.codex}/auth.json"
  else
    log "codex     MISSING  run: codex login"; missing=1
  fi
  # grok: x.ai subscription (auth.json) or XAI_API_KEY.
  if [[ -r "$HOME/.grok/auth.json" ]] || [[ -n "${XAI_API_KEY:-}" ]]; then
    log "grok      OK"
  else
    log "grok      MISSING  run: grok (sign in), or set XAI_API_KEY"; missing=1
  fi
  for p in nvidia cerebras; do
    case "$p" in
      nvidia)   v="${NVIDIA_API_KEY:-}" ;;
      cerebras) v="${CEREBRAS_API_KEY:-}" ;;
    esac
    if [[ -n "$v" ]] || grep -qE "^$(printf '%s' "${p}" | tr '[:lower:]' '[:upper:]')_API_KEY=." "$ROOT/env" 2>/dev/null; then
      log "$p  OK   $ROOT/grok-home-$p/config.toml"
    else
      log "$p  MISSING  no API key"; missing=1
    fi
  done
  return "$missing"
}

[[ "$CHECK_ONLY" == "1" ]] || provision
report
