#!/usr/bin/env bash
# Nightly codemap refresh (02:00 local, after every other nightly loop).
#
# tools/codemap/{codemap.json,codemap.data.js,architecture.json} are generated
# from the whole tree, so any branch that commits them conflicts with every
# other open branch. Feature branches never touch them; this job regenerates
# them from origin/main once a night, opens a PR, waits for the required
# checks, and squash-merges it.
#
# Runs in its own clone (never edit it by hand; every run hard-resets it):
#   bash scripts/setup_codemap_nightly.sh
set -euo pipefail

REPO="${RADON_CODEMAP_REPO:-$HOME/radon-weekend/radon-codemap}"
ARTIFACTS=(tools/codemap/codemap.json tools/codemap/codemap.data.js tools/codemap/architecture.json)
cd "$REPO"

LOCK="$REPO/.codemap-nightly.lock"
if ! mkdir "$LOCK" 2>/dev/null; then
  if kill -0 "$(cat "$LOCK/pid" 2>/dev/null)" 2>/dev/null; then
    echo "codemap-nightly: run in flight; skipping"
    exit 0
  fi
  rm -rf "$LOCK" && mkdir "$LOCK"
fi
echo $$ > "$LOCK/pid"
trap 'rm -rf "$LOCK"' EXIT

git fetch -q origin
git checkout -f -q main
git reset --hard -q origin/main

python3.13 tools/codemap/generate_codemap.py
# Generated maps belong only to this nightly branch.  Verify the regenerated
# checkout before deciding whether a refresh PR is needed, so a generator
# regression cannot silently publish stale or malformed import metadata.
CODEMAP_NIGHTLY=1 python3.13 -m pytest scripts/tests/test_codemap.py::TestCommittedArtifacts::test_matches_live_graph -q
if git diff --quiet -- "${ARTIFACTS[@]}"; then
  echo "codemap-nightly: fresh at $(git rev-parse --short HEAD)"
  exit 0
fi

# Timestamp-only refreshes do not justify a branch or a PR. Stage only the
# generated artifacts so the shared semantic classifier can inspect the exact
# proposed tree before publishing or superseding any existing refresh.
git add -- "${ARTIFACTS[@]}"
if python3.13 scripts/nightly_publish.py check --base HEAD --index; then
  :
else
  gate_rc=$?
  if [[ "$gate_rc" == 3 ]]; then
    echo "codemap-nightly: 0 PR(s), nothing to merge (no substantive graph changes)"
    exit 0
  fi
  exit "$gate_rc"
fi

BRANCH="codemap/$(date +%Y-%m-%d-%H%M)"
git checkout -q -b "$BRANCH"
git commit -q -m "chore(codemap): nightly refresh at $(git rev-parse --short origin/main)"
printf '%s\n' 'Generated by scripts/codemap_nightly.sh. Only tools/codemap artifacts change.' > "$LOCK/pr-body.md"
if python3.13 scripts/nightly_publish.py publish --base main --head "$BRANCH" \
  --title "chore(codemap): nightly refresh $(date +%Y-%m-%d)" \
  --body-file "$LOCK/pr-body.md"; then
  :
else
  publish_rc=$?
  if [[ "$publish_rc" == 3 ]]; then
    echo "codemap-nightly: 0 PR(s), nothing to merge (refresh already on main)"
    exit 0
  fi
  exit "$publish_rc"
fi

# Supersede an older refresh only after its substantive replacement exists.
gh pr list --state open --search "head:codemap/" --json number,headRefName \
  --jq ".[] | select(.headRefName | startswith(\"codemap/\")) | select(.headRefName != \"$BRANCH\") | .number" \
  | while IFS= read -r n; do gh pr close "$n" --delete-branch --comment "Superseded by tonight's refresh."; done

# Required checks must report before a merge is allowed.
sleep 60
gh pr checks "$BRANCH" --required --watch --interval 60
gh pr merge "$BRANCH" --squash --delete-branch
echo "codemap-nightly: merged $BRANCH"
