#!/usr/bin/env bash
# Nightly codemap refresh (02:00 local, after every other nightly loop).
#
# tools/codemap/{codemap.json,codemap.data.js,architecture.json} are generated
# from the whole tree, so any branch that commits them conflicts with every
# other open branch. Feature branches never touch them; this job regenerates
# them from origin/main once a night, opens a PR, waits for the required
# checks, and squash-merges it.
#
# Runs in its own clone (never edit it by hand; every run hard-resets it):
#   bash scripts/setup_codemap_nightly.sh
set -euo pipefail

REPO="${RADON_CODEMAP_REPO:-$HOME/radon-weekend/radon-codemap}"
ARTIFACTS=(tools/codemap/codemap.json tools/codemap/codemap.data.js tools/codemap/architecture.json)
cd "$REPO"

LOCK="$REPO/.codemap-nightly.lock"
if ! mkdir "$LOCK" 2>/dev/null; then
  if kill -0 "$(cat "$LOCK/pid" 2>/dev/null)" 2>/dev/null; then
    echo "codemap-nightly: run in flight; skipping"
    exit 0
  fi
  rm -rf "$LOCK" && mkdir "$LOCK"
fi
echo $$ > "$LOCK/pid"
trap 'rm -rf "$LOCK"' EXIT

git fetch -q origin
git checkout -f -q main
git reset --hard -q origin/main

python3.13 tools/codemap/generate_codemap.py
# Generated maps belong only to this nightly branch.  Verify the regenerated
# checkout before deciding whether a refresh PR is needed, so a generator
# regression cannot silently publish stale or malformed import metadata.
python3.13 -m pytest scripts/tests/test_codemap.py::TestCommittedArtifacts::test_matches_live_graph -q
if git diff --quiet -- "${ARTIFACTS[@]}"; then
  echo "codemap-nightly: fresh at $(git rev-parse --short HEAD)"
  exit 0
fi

# An unmerged PR from a previous night is superseded by this one.
gh pr list --state open --search "head:codemap/" --json number,headRefName \
  --jq '.[] | select(.headRefName | startswith("codemap/")) | .number' \
  | while IFS= read -r n; do gh pr close "$n" --delete-branch --comment "Superseded by tonight's refresh."; done

BRANCH="codemap/$(date +%Y-%m-%d-%H%M)"
git checkout -q -b "$BRANCH"
git add -- "${ARTIFACTS[@]}"
git commit -q -m "chore(codemap): nightly refresh at $(git rev-parse --short origin/main)"
git push -q -u origin "$BRANCH"
gh pr create --base main --head "$BRANCH" \
  --title "chore(codemap): nightly refresh $(date +%Y-%m-%d)" \
  --body "Generated by scripts/codemap_nightly.sh. Only tools/codemap artifacts change."

# Required checks must report before a merge is allowed.
sleep 60
gh pr checks "$BRANCH" --required --watch --interval 60
gh pr merge "$BRANCH" --squash --delete-branch
echo "codemap-nightly: merged $BRANCH"
