[Service]
User=root
NotifyAccess=all
Environment=RADON_RUNTIME=container
Type=simple
WatchdogSec=infinity
ExecStartPre=
ExecStart=
ExecStart=/usr/local/sbin/radon-app-runtime run %n
ExecStopPost=/usr/local/sbin/radon-app-runtime stop %n
