[Service]
User=root
Environment=RADON_RUNTIME=container
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Type=simple
ExecStartPre=
ExecStart=
ExecStart=/usr/local/sbin/radon-app-runtime run %n
ExecStopPost=/usr/local/sbin/radon-app-runtime stop %n
